workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m2
    scripts:
      - cd fardja
      - chmod +x gradlew
      - ./gradlew app:assembleRelease
    artifacts:
      - fardja/app/build/outputs/apk/release/*.apk
