workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m2
    scripts:
      - ls -la
      - gradle assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
      - app/build/outputs/apk/release/*.apk
